// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.DAL;

namespace PMS.DAL.Migrations
{
    [DbContext(typeof(PMSContext))]
    partial class PMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMS.DAL.Entity.Allergy", b =>
                {
                    b.Property<int>("Allergy_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Allerginicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Clinical_Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Allergy_Id");

                    b.ToTable("Allergy");
                });

            modelBuilder.Entity("PMS.DAL.Entity.Appointment", b =>
                {
                    b.Property<int>("Appointment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Appointment_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Appointment_Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Nurse_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Physician_Id")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Schedular_Id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Appointment_Id");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("PMS.DAL.Entity.Diagnosis", b =>
                {
                    b.Property<int>("Diagnosis_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnosis_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Diagnosis_Is_Depricated")
                        .HasColumnType("bit");

                    b.HasKey("Diagnosis_Id");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("PMS.DAL.Entity.DrugData", b =>
                {
                    b.Property<int>("Drug_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Drug_Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Generic_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Manufacture_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Strength")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Drug_ID");

                    b.ToTable("DrugData");
                });

            modelBuilder.Entity("PMS.DAL.Entity.Procedure", b =>
                {
                    b.Property<int>("Procedure_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Procedure_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedure_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Procedure_Is_Depricated")
                        .HasColumnType("bit");

                    b.HasKey("Procedure_ID");

                    b.ToTable("Procedure");
                });

            modelBuilder.Entity("PMS.DAL.Entity.Registration", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoggedin")
                        .HasColumnType("bit");

                    b.Property<bool?>("Is_SetDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Known_Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("PMS.DAL.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
